[package]
authors = ["Ronan Forman <ronan131@gmail.com>"]
name = "year2018"
version = "0.1.0"

[dependencies]
chrono = "0.4"
itertools = "0.7"
num-derive = "0.2"
num-traits = "0.2"
pathfinding = "2.2.2"
regex = "1"
